apiVersion: apps/v1
kind: Deployment
metadata:
  name: extranet-front-deployment
  namespace: extranet-testing
  labels:
    app: extranet-front
spec:
  selector:
    matchLabels:
      app: extranet-front
      tier: extranet
  replicas: 1 # indica al controlador que ejecute 2 pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: extranet-front
        tier: extranet
    spec:
      containers:
      - name: angular
        #image: grupopreving/avansis-extranet-front-demo:20220818v3
        image: <DOCKER_HUB_PROFILE>/<IMAGE_VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
#        volumeMounts:
#            - mountPath: /home/preving/app/recursos
#              name: recursos
#      volumes:
#        - name: recursos
#          persistentVolumeClaim:
#            claimName: app-recursos-testing
      imagePullSecrets:
      - name: preving-docker-hub
